# Generated by Django 4.0.4 on 2022-05-10 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicaoEnsino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicaoensino',
            name='cnpj',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='info_relevante',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
