# Generated by Django 4.0.3 on 2022-05-24 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0002_alter_endereco_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeConcedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(17)])),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('telefone_fixo', models.CharField(max_length=25)),
                ('telefone_cel', models.CharField(max_length=25, null=True)),
                ('representante', models.CharField(max_length=255)),
                ('cargo_representante', models.CharField(max_length=255)),
                ('cpf_representante', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(14)])),
                ('info_relevantes', models.CharField(max_length=255, null=True)),
                ('eh_agencia_integradora', models.BooleanField(default=False)),
                ('endereco', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidade_concedente_endereco', to='endereco.endereco')),
            ],
        ),
    ]
