# Generated by Django 4.0.3 on 2022-05-24 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('endereco', '0002_alter_endereco_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(14)])),
                ('telefone_fixo', models.CharField(max_length=25)),
                ('telefone_cel', models.CharField(max_length=25, null=True)),
                ('nome_do_pai', models.CharField(max_length=255)),
                ('nome_da_mae', models.CharField(max_length=255)),
                ('matriculado', models.BooleanField(default=True)),
                ('numero_matricula', models.CharField(max_length=255, null=True)),
                ('representante_legal', models.CharField(max_length=255, null=True)),
                ('rg_rep_legal', models.CharField(max_length=45, null=True)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estagiario_curso', to='curso.curso')),
                ('endereco', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estagiario_endereco', to='endereco.endereco')),
            ],
        ),
    ]
