# Generated by Django 4.0.3 on 2022-05-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidadeConcedente', '0001_initial'),
        ('estagiario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=255)),
                ('cargo_supervisor', models.CharField(max_length=255)),
                ('formacao_academica', models.CharField(max_length=255)),
                ('tempo_experiencia', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('anofase', models.CharField(max_length=255)),
                ('horario_estagio', models.CharField(max_length=255)),
                ('jornada_semanal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carga_horaria_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_vale_transporte', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('setor_ou_area', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('num_apolice_seguro', models.CharField(max_length=255, null=True)),
                ('tipo_estagio', models.CharField(max_length=255)),
                ('tem_agencia_integradcao', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ATIVO', 'Estágio Ativo'), ('INATIVO', 'Estágio Inativo'), ('RESCINDIDO', 'Estágio Inativo Rescindido')], default='ATIVO', max_length=10)),
                ('nome_agencia_integracao', models.CharField(max_length=255, null=True)),
                ('rquadrimestral1', models.BooleanField(default=False)),
                ('rquadrimestral2', models.BooleanField(default=False)),
                ('rquadrimestral3', models.BooleanField(default=False)),
                ('rquadrimestral4', models.BooleanField(default=False)),
                ('rquadrimestral5', models.BooleanField(default=False)),
                ('rquadrimestral6', models.BooleanField(default=False)),
                ('estagiario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estagio_estagiario', to='estagiario.estagiario')),
                ('unidadeConcedente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estagio_unidade_concedente', to='unidadeConcedente.unidadeconcedente')),
            ],
        ),
    ]
