# Generated by Django 4.0.3 on 2022-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='carga_horaria_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='jornada_semanal',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='valor_vale_transporte',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
