# Generated by Django 4.0.3 on 2022-05-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicaoEnsino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('turno', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('NOT', 'Noturno')], max_length=3)),
                ('modalidade', models.CharField(max_length=255)),
                ('instituicaoEnsino', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curso_instituicao', to='instituicaoEnsino.instituicaoensino')),
            ],
        ),
    ]
